runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 3

env_variables:
  NODE_ENV: 'production'
handlers:
  - url: /.*
    script: auto
    secure: always
